In [18]:
import numpy as np
#extracting data from csv files into numpy arrays
from numpy import genfromtxt
x_train = genfromtxt('train_data.csv', delimiter=',')
y_train = genfromtxt('train_labels.csv', delimiter=',')
x_test = genfromtxt('test_data.csv', delimiter=',')
y_test = genfromtxt('test_labels.csv', delimiter=',')

In [53]:
x_undefined = genfromtxt('undefined4_data.csv', delimiter=',')
y_undefined = genfromtxt('undefined4_labels.csv',delimiter=',')

In [54]:
x_undefined = np.reshape(x_undefined,(x_undefined.shape[0], 40,1,1))

In [55]:
x_undefined.shape,y_undefined.shape

((33, 40, 1, 1), (33,))

In [19]:
#shape
x_train.shape,x_test.shape,y_train.shape,y_test.shape

((878, 40), (210, 40), (878,), (210,))

In [20]:
import random
tmp = [[x,y] for x, y in zip(x_train, y_train)]
tmp2 = [[x,y] for x, y in zip(x_test, y_test)]
random.shuffle(tmp)
random.shuffle(tmp2)
x_train = [n[0] for n in tmp]
y_train = [n[1] for n in tmp]
x_test = [n[0] for n in tmp2]
y_test = [n[1] for n in tmp2]
x_train = np.array(x_train)
x_test = np.array(x_test)
y_train=np.array(y_train)
y_test=np.array(y_test)
x_train.shape,x_test.shape,y_train.shape,y_test.shape
x_train.shape,y_train.shape

((878, 40), (878,))

In [21]:
#converting to one hot
from keras.utils.np_utils import to_categorical
y_train = to_categorical(y_train, num_classes=3)
y_test = to_categorical(y_test, num_classes=3)
y_train.shape,y_test.shape

((878, 3), (210, 3))

In [22]:
#reshaping to 2D 
x_train=np.reshape(x_train,(x_train.shape[0], 40,1))
x_test=np.reshape(x_test,(x_test.shape[0], 40,1))
x_train.shape,x_test.shape

((878, 40, 1), (210, 40, 1))

In [23]:
#reshaping to shape required by CNN
x_train=np.reshape(x_train,(x_train.shape[0], 40,1,1))
x_test=np.reshape(x_test,(x_test.shape[0], 40,1,1))

In [24]:
from keras import Sequential
from keras.layers import Dense,Conv2D,MaxPooling2D,Flatten,Dropout

In [25]:
#forming model
model=Sequential()

In [26]:
model.add(Conv2D(32,(3*3),padding="Same",activation="relu",input_shape=(40,1,1)))
model.add(MaxPooling2D(padding="same"))

model.add(Conv2D(64,(3*3),padding="same",activation="relu"))
model.add(MaxPooling2D(padding="same"))
model.add(Dropout(0.25))

model.add(Conv2D(128,(3*3),padding="same",activation="relu"))
model.add(MaxPooling2D(padding="same"))
model.add(Dropout(0.25))

model.add(Flatten())

model.add(Dense(3,activation="softmax"))

In [27]:
#compiling
model.compile(optimizer="adam",loss="categorical_crossentropy",metrics=["accuracy"])

In [28]:
#training the model
model.fit(x_train,y_train,batch_size=5,epochs=20,validation_data=(x_test,y_test))

Epoch 1/20
176/176 [==============================] - 1s 6ms/step - loss: 0.5477 - accuracy: 0.7927 - val_loss: 0.2697 - val_accuracy: 0.9190
Epoch 2/20
176/176 [==============================] - 1s 5ms/step - loss: 0.2887 - accuracy: 0.8884 - val_loss: 0.2238 - val_accuracy: 0.9333
Epoch 3/20
176/176 [==============================] - 1s 5ms/step - loss: 0.2478 - accuracy: 0.9146 - val_loss: 0.1545 - val_accuracy: 0.9571
Epoch 4/20
176/176 [==============================] - 1s 5ms/step - loss: 0.2182 - accuracy: 0.9146 - val_loss: 0.3116 - val_accuracy: 0.8667
Epoch 5/20
176/176 [==============================] - 1s 5ms/step - loss: 0.2223 - accuracy: 0.9203 - val_loss: 0.1483 - val_accuracy: 0.9476
Epoch 6/20
176/176 [==============================] - 1s 5ms/step - loss: 0.1340 - accuracy: 0.9431 - val_loss: 0.5570 - val_accuracy: 0.8238
Epoch 7/20
176/176 [==============================] - 1s 5ms/step - loss: 0.1423 - accuracy: 0.9476 - val_loss: 0.0935 - val_accuracy: 0.9714
Epoch 

In [29]:
model.save('outside_model3.h5')

In [30]:
#train and test loss and scores respectively
train_loss_score=model.evaluate(x_train,y_train)
test_loss_score=model.evaluate(x_test,y_test)
print(train_loss_score)
print(test_loss_score)

7/7 [==============================] - 0s 3ms/step - loss: 0.1484 - accuracy: 0.9619
[0.014404568821191788, 0.9965831637382507]
[0.148354172706604, 0.961904764175415]


In [31]:
pred = model.predict(x_test)

In [32]:
pred

array([[9.99999642e-01, 1.59688849e-08, 3.13933015e-07],
       [1.70846803e-07, 1.47230249e-11, 9.99999881e-01],
       [7.32335393e-05, 2.86881436e-06, 9.99923944e-01],
       [1.65107705e-09, 1.00000000e+00, 7.46018269e-09],
       [1.00000000e+00, 9.27453576e-14, 5.91412164e-09],
       [9.99999881e-01, 3.25572138e-08, 8.71198083e-08],
       [1.00000000e+00, 1.01513309e-20, 9.64411861e-18],
       [1.00000000e+00, 9.57110201e-20, 6.29552407e-17],
       [1.41517200e-14, 8.93476652e-04, 9.99106467e-01],
       [1.00000000e+00, 5.02022646e-09, 4.09625622e-09],
       [1.00000000e+00, 1.30189913e-12, 1.44503742e-08],
       [9.80469525e-12, 7.23780036e-10, 1.00000000e+00],
       [9.99999881e-01, 2.61609762e-10, 7.20133002e-08],
       [1.00000000e+00, 1.75041622e-13, 1.13139609e-09],
       [9.99548376e-01, 1.77550337e-05, 4.33842913e-04],
       [9.99994278e-01, 6.10650446e-08, 5.64308220e-06],
       [9.99644876e-01, 3.53006326e-04, 2.15992441e-06],
       [2.04069261e-03, 9.94266

In [33]:
from sklearn import metrics

y_true = []
y_pred = []
max = 0
max_index = 0
for i in range(len(pred)):
    for j in range(len(pred[i])):
        if(pred[i][j]>max):
            max = pred[i][j]
            max_index = j
    #if(max>0.9):        
    #    y_pred.append(max_index)
    #else:
     #   y_pred.append(3)
    y_pred.append(max_index)
    max = 0
    
    
for i in range(len(y_test)):
    for j in range(len(y_test[i])):
        if(y_test[i][j]>max):
            max = pred[i][j]
            max_index = j
    #if(max>0.9):        
     #   y_true.append(max_index)
    #else:
     #   y_true.append(3)
    y_true.append(max_index)
    max = 0

In [33]:
y_pred

array([2, 1, 3, 1, 1, 1, 0, 1, 1, 0, 2, 1, 2, 2, 1, 1, 1, 3, 1, 1, 1, 1,
       0, 0, 2, 0, 0, 1, 3, 1, 1, 0, 1, 1, 2, 2, 1, 1, 1, 0, 1, 2, 1, 1,
       1, 3, 1, 0, 0, 1, 1, 0, 3, 1, 1, 1, 2, 2, 1, 0, 1, 2, 0, 3, 0, 2,
       0, 3, 1, 1, 1, 1, 0, 1, 1, 3, 1, 0, 2, 0, 1, 0, 3, 0, 3, 0, 3, 2,
       0, 0, 3, 1, 3, 1, 1, 1, 1, 0, 2, 1, 3, 2, 0, 0, 2, 1, 3, 1, 0, 2,
       3, 0, 1, 1, 1, 2, 1, 0, 1, 1, 2, 1, 3, 1, 1, 0, 1, 0, 2, 1, 0, 3,
       1, 0, 0, 3, 0, 0, 1, 0, 0, 1, 0, 1, 0, 3, 1, 0, 1, 0, 3, 1, 2, 1,
       0, 0, 0, 0, 3, 0, 1, 1, 1, 1, 0, 2, 2, 2, 0, 0, 2, 0, 0, 0, 1, 3,
       3, 1, 1, 1, 0, 1, 0, 1, 3, 1, 3, 2, 1, 3, 2, 1, 1, 3, 1, 0, 0, 3,
       3, 0, 2, 2, 0, 3, 0, 0, 0, 1, 2, 3])

In [34]:
y_true

array([2, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 2, 2, 2, 1, 1, 1, 0, 1, 1, 1, 1,
       0, 0, 2, 0, 0, 1, 2, 1, 1, 0, 1, 1, 2, 2, 1, 1, 1, 0, 1, 2, 1, 1,
       1, 0, 1, 0, 0, 1, 1, 0, 2, 1, 1, 1, 2, 2, 1, 0, 1, 2, 0, 1, 0, 2,
       0, 2, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 2, 0, 2, 2,
       0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 2, 1, 2, 2, 0, 0, 2, 1, 2, 1, 0, 2,
       0, 0, 1, 1, 1, 2, 1, 0, 1, 1, 2, 1, 0, 1, 1, 0, 1, 0, 2, 1, 0, 0,
       1, 0, 0, 0, 2, 0, 1, 0, 0, 1, 0, 1, 0, 2, 1, 0, 1, 0, 1, 1, 2, 1,
       0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 2, 2, 2, 0, 0, 2, 0, 0, 0, 1, 0,
       0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 2, 1, 2, 2, 1, 1, 0, 1, 0, 0, 0,
       0, 0, 2, 2, 0, 0, 0, 0, 0, 1, 2, 0])

In [87]:
undefined_y_true = []
undefined_y_pred = []
max = 0
max_index = 0
for i in range(len(undefined_pred)):
    for j in range(len(undefined_pred[i])):
        if(undefined_pred[i][j]>max):
            max = undefined_pred[i][j]
            max_index = j
    if(max>0.7):        
        undefined_y_pred.append(max_index)
    else:
        undefined_y_pred.append(3)
    max = 0

In [88]:
undefined_y_pred

[3,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 3,
 3,
 2,
 3,
 0,
 2,
 2,
 0,
 2,
 1,
 1,
 1,
 3,
 3,
 3,
 2,
 1,
 3,
 3,
 3,
 3,
 1,
 3,
 1,
 3]

In [34]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
y_true = np.array(y_true)
y_pred = np.array(y_pred)
target_names = ['car-horn', 'dog-bark', 'fire-alarm']
print(confusion_matrix(y_true, y_pred))
print(classification_report(y_true, y_pred))

[[78  0  2]
 [ 1 89  0]
 [ 2  3 35]]
              precision    recall  f1-score   support

           0       0.96      0.97      0.97        80
           1       0.97      0.99      0.98        90
           2       0.95      0.88      0.91        40

    accuracy                           0.96       210
   macro avg       0.96      0.95      0.95       210
weighted avg       0.96      0.96      0.96       210

